import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from 'react';
import { useAccount, useConnect, useContractRead, useNetwork } from 'wagmi';
import { fetchBalance, getContract, readContract } from '@wagmi/core';
import { boxAbi } from '@/abi/box.abi';

import abig from '../abi/GovernorContract.json'

import { governorContractAbi } from '@/abi/governorContract.abi';
import { Propose } from '@/components/propose';
export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] = useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};

	// const { data, isError, isLoading } = useContractRead({
	// 	address: '0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9',
	// 	abi: governorContractAbi,
	// 	functionName: 'vot',
	// 	chainId: 31337
	// });

	// const { data, isError, isLoading } = useContractRead({
	// 	address: '0x31403b1e52051883f2Ce1B1b4C89f36034e1221D',
	// 	abi: boxAbi,
	// 	functionName: 'retrieve',
	// 	chainId: 31337
	// });


	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className={styles.backdrop}
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className={styles.header}>
					<div className={styles.logo}>
						<Image
							src="/logo.svg"
							alt="WalletConnect Logo"
							height="32"
							width="203"
						/>
					</div>
					<div className={styles.buttons}>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isNetworkSwitchHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-network-button />
						</div>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isConnectHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-button />
						</div>
					</div>
				</div>
			</header>
			<main className={styles.main}>
				<Propose />
			</main>
		</>
	);
}
